# Uncomment the next line to define a global platform 
# for your project
platform :ios, '10.0'

target 'RxContainerExample' do

  # Comment the next line if you're not using Swift and 
  # don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 4.0.0-alpha.1'
  pod 'RxContainer', :path => '../'
  pod 'SwiftLint', :configurations => ['Debug']
  pod 'Reveal-SDK', :configurations => ['Debug']

end
